server:
  context-path: /
  port: 8094

# jdbc
spring:
  datasource:
    url: jdbc:oracle:thin:@//10.196.68.204:1621/njdx_njracdb2
    username: fangan_activiti
    password: H6tfVIZ2
  messages:
    basename: msg/messages-pro,msg/messages

#dubbo config
dubbo:
  zookeeper:
    address: 10.101.86.121:2181
  version:


  #spring boot admin
  boot:
    admin:
      url: http://10.101.86.121:8092
      client:
        name: activiti-rest
        prefer-ip: true
