server:
  context-path: /
  port: 8080

# jdbc
spring:
  datasource:
    url: jdbc:oracle:thin:@172.16.0.142:1521:zhfadb
    username: activiti
    password: activitipasswd2018

# messageSource
spring:
  messages:
    basename: msg/messages-pro,msg/messages